### ISSUE TITLE
Getting error in running semi.sup on linux platform

### ISSUE THREAD

**Issue by raagbtitl** [yufree/apLCMS#1]
Tried to run on Linux platform and getting following error:

**Commands used:**
> library("apLCMS")
> loc="/Work/aplcmsdata"
> setwd(loc)
> cdf.files = list.files(loc, ".mzML", ignore.case = TRUE)
> cdf.files = tolower(cdf.files)
> known=read.csv("/Work /known.table.hplus.csv")

> aR=semi.sup(
+   loc,
+   file.pattern = ".mzML",
+   known.table = known,
+   n.nodes = 2,
+   min.exp = 1,
+   min.pres = 1,
+   min.run = 12,
+   mz.tol = 1e-05
+ )

Error:
***************************** prifiles --> feature lists *****************************
number of files to process: 2
NA_1_12_1e-05_0_bi-Gaussian_0.01_500_0.01_1_0.01_100_NA_NA_.feature  Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'NA_1_12_1e-05_0_bi-Gaussian_0.01_500_0.01_1_0.01_100_NA_NA_.feature', probable reason 'No such file or directory'

**Comment by yufree** [comment]
This error means the software could not find files in your working dictionary. I wonder why you have `tolower` to process the path? Could you output `cdf.files` ?

p.s. I am not the author of this package.

**Comment by raagbtitl** [comment]
This problem , I am only getting in CentOS platform not in Windows. I also tried with without tolower, it does not work , however tolower does not affect the outcome as I assigned ignore.case as TRUE.

cdf.files output:
>cdf.files
[1] "/Work/aplcmsdata/Blanc_04.mzXML"
[2] "/Work/aplcmsdata/Blanc_12.mzXML"
[3] "/Work/aplcmsdata/HU_034.mzXML"
[4] "/Work/aplcmsdata/HU_051.mzXML"

**Comment by yufree** [comment]
Well, I think you could change `cdf.files = list.files(loc, ".mzML", ignore.case = TRUE)` into `cdf.files = list.files(loc, ".mzXML", ignore.case = TRUE)`. `mzML` and `mzXML` are actually different file extension.

**Comment by raagbtitl** [comment]
Sorry for misunderstanding, I tried both mzML and mzXML, thats why I put mzXML files. While running i wrote correct file format in list.files command.

**Comment by raagbtitl** [comment]
Went more deeper tried to check with proc.cdf() which is first primary step of semi.sup() and got following errors:

> this.spectrum<-proc.cdf("HU_034.mzXML", min.pres = 0.5, min.run = 12, tol = 1e-5)
Error in object@backend$getAllScanHeaderInfo() :
  [SpectrumList_mzXML::spectrum()] Error seeking to <scan>.

> this.spectrum<-proc.cdf("HU_051.mzXML", min.pres = 0.5, min.run = 12, tol = 1e-5)
Error: Can not open file HU_051.mzXML! Original error was: Error in pwizModule$open(filename): 
[SAXParser::parse()] Empty tag at offset 7806822.

> proc.cdf("HU_neg_078.mzXML", min.pres = 0.5, min.run = 12, tol = 1e-5)
Error in UseMethod("close") :
  no applicable method for 'close' applied to an object of class "c('mzRpwiz', 'mzR', 'Versioned')"

**Comment by yufree** [comment]
Could you try `mz.conn<-openMSfile("HU_051.mzXML")` ?  I wonder if this issue came from the mzR or the file itself.

**Comment by egottschalk** [comment]
I am seeing the same error message from proc.cdf:

`Error in UseMethod("close") : 
  no applicable method for 'close' applied to an object of class "c('mzRpwiz', 'mzR', 'Versioned')"`

The underlying mzR functionality seems to be work:

`mz.conn<-openMSfile("XXXXX.mzXML")`
`close(mz.conn)`

Any idea what could be going on here?

**Comment by yufree** [comment]
I think you could comment this part in the source code, re-install the package and try again. `mzR` has some updates and I am not sure if some methods changed for their objects.

https://github.com/yufree/apLCMS/blob/d9bfaa525258b164a7bd348f8454f9662032c53b/R/load.lcms.R#L65

**Comment by egottschalk** [comment]
That seem to fix things, thanks.

If you want to add me as a collaborator to the project, I can push a branch with the update.

**Comment by yufree** [comment]
Sure and I added you as a collaborator. This repo is not the official repo and I am not the author of this package.  However, I am happy to see this repo has no error issue.
